### ISSUE TITLE
Set Tile (Device) Names based on Name from nodejs-poolController

### ISSUE THREAD

**Issue by arrmo** [bsileo/SmartThings_Pentair#15]
Use the naming that is provided in the API, rather than just generic names?

**Comment by bsileo** [comment]
@arrmo This is supported already - set the "Autoname" setting to true in the Pool Controller device. It will pickup these names the next time Circuits are updated form the PoolController. This is a one-time update only, allowing the ST user to subsequently adjust these to names that work better in the ST platform.

**Comment by arrmo** [comment]
OK, my bad - I admit, I misunderstood. Why is this "one-time only" then? I admit, I took that to mean it was an initial device creation option, not "run-time". Or does that mean it sets it, but if you overwrite it then it will no longer update? Or, even if you set a name, but then subsequently enable this option ... it will overwrite (once)? Just trying to understand.

Thanks!

**Comment by bsileo** [comment]
Its one time - as-in when you turn it on, it will update the names once from the poolController then disable this setting. It is not able to determine if you have changed the name in Smartthings, etc. so that is why we just run this once when the user changes that option to "On" in the Device settings.

**Comment by arrmo** [comment]
Makes perfect sense - thanks!
