### ISSUE TITLE
Switch State stuck on TURNING ON

### ISSUE THREAD

**Issue by kirkmster** [bsileo/SmartThings_Pentair#32]
Within the Smart Things Classic app, all switches in the SmartThings-Pentair app when toggled from Off to On get stuck in the TURNING ON state.  In nodejs-poolController logs, I see the on event and the device does turn on and everything appears to be working in the nodesjs-poolController UI. It appears the confirmation in not making back to the SmartApp and state get out of sync from there SmartThings. Configuration is the 93cc4b version of nodesjs-poolcontroller,  ce2adb of SmartThings_Pentair, V3 SmartHub. Tried the Added some debug and haven't found anything yet but its unclear to me how the state update works. New to SmartThings and groovy,  Any recommendations appreciated.

**Comment by bsileo** [comment]
Sorry for the delay on this...missed some updates during the non pool season!  Does the state get corrected when you hit the "Refresh" button in the PoolControler device in ST? This sync issues is happening because updates are not going from NJS-PoolController to SmartThings correctly to update it on the state. You can look in the Live Logging on SmartThings IDE to see if there are any errors showing up from the PoolController device when you toggle the status of one of the switches.
